{% set name = "latexdiff" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ftilmann/{{ name }}/archive/{{ version }}.tar.gz
  sha256: fe28ed8586c77fbdc74911db44cbe81d7b7216b361d4df54692c0c3c5ff449c4

build:
  number: 1
  noarch: generic
  script:
    - cp {{ name }} {{ name }}-vc $PREFIX/bin/

requirements:
  build:
    - make
  host:
    - perl
  run:
    - perl
    - perl-algorithm-diff

test:
  commands:
    - latexdiff --version 2>&1 | grep {{ version }}
    - latexdiff-vc --version

about:
  home: https://github.com/ftilmann/{{ name }}
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Compares two latex files and marks up significant differences between them

extra:
  recipe-maintainers:
    - tdegeus
