{% set name = "latexdiff" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ftilmann/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 3e8ccb023bcb8c0047b86b0f395ba967a26a2efdc6923a60c50fdd97b8e43201

build:
  number: 0
  noarch: generic
  script:
    - cp {{ name }} $PREFIX/bin/

requirements:
  build:
    - make
  host:
    - perl
  run:
    - perl
    - perl-algorithm-diff

test:
  commands:
    - latexdiff --version 2>&1 | grep {{ version }}

about:
  home: https://github.com/ftilmann/{{ name }}
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Compares two latex files and marks up significant differences between them

extra:
  recipe-maintainers:
    - tdegeus
