schema_version: 1

context:
  version: "1.3.4"

package:
  name: latexdiff
  version: ${{ version }}

source:
  url: https://github.com/ftilmann/latexdiff/archive/${{ version }}.tar.gz
  sha256: f56afb9863ee9d5abc411bb947c89bdbc07070a928a5420d86e40e351fa41b94

build:
  number: 0
  noarch: generic
  script:
    - cp latexdiff latexdiff-vc $PREFIX/bin/

requirements:
  build:
    - make
  host:
    - perl
  run:
    - perl
    - perl-algorithm-diff

tests:
  - script:
      - latexdiff --version 2>&1 | grep ${{ version }}
      - latexdiff-vc --version

about:
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Compares two latex files and marks up significant differences between them
  homepage: https://github.com/ftilmann/latexdiff

extra:
  recipe-maintainers:
    - tdegeus

